### ISSUE TITLE
Difference between R and Python module

### ISSUE THREAD

**Issue by ZijieZhaoMMHW** [robwschlegel/heatwaveR#8] opened 2019-01-22 05:10 UTC
Hi Robert.

Your `heatwaveR` package is a very good work, I am currently developing a MATLAB package for heatwave analysis, your work  actually inspires me a lot. Many thanks. I would try to get it as complete as yours 👍 

However, I wonder if you notice that the calculated climatologies by python and R could be different due to the different way to deal with Feb29. If you read Eric's python code, you would find something like
```
# Special case for Feb 29
    thresh_climYear[feb29-1] = 0.5*thresh_climYear[feb29-2] + 0.5*thresh_climYear[feb29]
    seas_climYear[feb29-1] = 0.5*seas_climYear[feb29-2] + 0.5*seas_climYear[feb29]
```

So Eric firstly calculates other climatologies, then use the average between Feb28 and Mar1 to calculate the climatology on Feb29.

In your R code, you actually deal with this in another way, which is firstly filling every noleap year's Feb29 by the mean of Feb28 and Mar1, then calculating the climatology. It would get a different result.

Just pointing out this issue for your consideration. I notice that you are preparing a "Detecting marine heatwaves" paper so maybe this issue is notable?

If you are ok with everything please feel free to close this issue.

Best wishes to your career, thanks for your generous share of your work.

Cheers,
Zijie

**Comment by robwschlegel** [comment] 2019-01-22 19:14
Hello Zijie,
Thank you for your interest in heatwaveR and for extending the MHW algorithm to MATLAB!
I would be happy to provide a link to the MATLAB module you created (https://github.com/ZijieZhaoMMHW/m_mhw1.0) in the heatwaveR documentation if you'd like.
I remember having seen this issue you found about 'feb29' once before when we first wrote the R translation. I recall that we decided that the way in which R handles this issue was preferable because it was better to first calculate feb29 for the time series, and then use that to calculate the climatologies. I'll look into how large of a difference this causes. I was going to be meeting with Eric Oliver already tomorrow so will discuss it with him then.
Once we have decided on and implemented a course of action I will close this issue.
Cheers,
-Rob

**Comment by ajsmit** [comment] 2019-01-22 20:06
Hmmm, interesting. I’d be keen to see the difference it’s going to make. My
guess is it’s going to shave off a few hundredths of a decimal in the
correlation between the R and python outputs. The real test of course is
not the correlation, between climatologists, but to check and see if the
detected events are going to be the same or not.

— A/Prof. AJ Smit | Department of Biodiversity & Conservation Biology
| University
of the Western Cape | Private Bag X17 | Bellville 7535 | South Africa
Work tel.: +27 21 959 3783 <//+27 21 959 3783> | Fax.: +27 21 959 2312
<//+27 21 959 2312> | Mobile: +27 78 300 6005 <//+27 78 300 6005>


GitHub:

https://github.com/ajsmit


R packages:

https://github.com/ajsmit/RmarineHeatWaves

https://robwschlegel.github.io/heatwaveR

**Comment by ZijieZhaoMMHW** [comment] 2019-01-22 21:42
Thanks @robwschlegel @ajsmit . Please also mention it in this issue when you decide the final way to deal with Feb29 so that I could make similar change to my code to gain consistent results.

Zijie

**Comment by robwschlegel** [comment] 2019-01-23 19:37
@ZijieZhaoMMHW , I looked into the issue of the 'feb29' values and found the differences they causd to be very negligible. I included the analysis in this [vignette](https://robwschlegel.github.io/MHWdetection/articles/r_vs_python.html#february-29th). I'm going to close this issue for now.

@ajsmit The small difference in 'feb29' has never caused a difference in event detection that I have been able to reproduce. What does cause differences in the detection of events is the presence of missing data. Eric Oliver and I are going to sit down together on Friday to go over the source code of both languages step by step to see where exactly this is having the largest effect.

**Closed as completed by robwschlegel** 2019-01-23 19:37 UTC
